# to run streamlit app type the following command in terminal: streamlit run 01_streamlit/🏠_Home.py

import streamlit as st 


st.header("ABOUT THE PROJECT")

st.write("This project was developed over two extended weekends in the spring of 2024 to showcase a complete data science project lifecycle, encompassing exploratory data analysis (EDA), feature engineering, model creation, and deployment of the entire solution as a web application. To maintain conciseness, several steps in exploratory data analysis have been condensed or omitted.")

st.write("Feature engineering encompassed the creation of additional categorical geospatial features, such as zip code groups, which have been utilized to improve data comprehension and enhance the accuracy of inferences generated by linear models. Predictions are made by the three best models selected from the PyCaret run, with only minimal model tuning performed due to constraints on compute resources.")

st.write("This dataset consists of historical housing prices obtained from Zillow, as referenced in the book ‘Practical Statistics for Data Scientists’ by Peter Bruce, Andrew Bruce, and Peter Gedeck. It’s essential to emphasize that this dataset does not reflect current market conditions; rather, it serves solely for demonstration purposes.")

st.warning("At no time should you depend on any predictions generated by this app.")

st.write("This project has used the following stack: Python, PyCaret, Docker, Statsmodels, Plotly. ")

github = "https://github.com/evgenyChudaev/HousingPricesPredictions"
st.write("Link to project [GitHub](%s)" % github)



col1, col2 = st.columns(2)

with col1:    
    st.image("./01_streamlit/images/PyCaret.png", use_column_width="always")
    st.image("./01_streamlit/images/Python.png", use_column_width="always")
    
with col2:    
    st.image("./01_streamlit/images/Streamlit.png", use_column_width="always")
    st.image("./01_streamlit/images/docker2.png", use_column_width="always")

    
